### ISSUE TITLE
Prewas unable to install in R

### ISSUE THREAD

**Issue by hsinjou0714** [Snitkin-Lab-Umich/prewas#8]
Hi,
I am using R version 4.0.3 and trying to install prewas. However, it keep showing that it is not available in this version. Is there a repository CRAN that I could download from?
![image](https://user-images.githubusercontent.com/40838554/110854220-7f121300-8269-11eb-9906-d8cc35c2a2b9.png)

For the vcf file input, If I'm generating a matrix for 300 ~500 strains for input of TreeWAS. Is there a tool you would recommend for generating this input?
Thank you!
Christine

**Comment by katiesaund** [comment]
Hi Christine, 

Prewas was temporarily removed from CRAN because a dependency (vcfR package) was archived on CRAN. Since then, the dependency has been updated. I just resubmitted prewas and therefore it should be back up on CRAN in a few days. I'll update here once prewas can be installed through CRAN again. Until then you can use the command: 
`devtools::install_github('Snitkin-Lab-Umich/prewas')` to install prewas on your computer.

Prewas should be just the tool you need to generate your input for TreeWAS.

-Katie

**Comment by hsinjou0714** [comment]
Thank you! It is successfully download!

**Comment by katiesaund** [comment]
Prewas is now available on CRAN.
